version: '3.9'
services:
   db:
      container_name: postgres
      image: postgres
      volumes:
         - ./data/db:/var/lib/postgresql/data
      environment:
         - POSTGRES_PASSWORD=postgres
         - POSTGRES_DB=postgres
         - POSTGRES_USER=postgres
         - POSTGRES_SERVICE=postgres
         - POSTGRES_PORT=5432
      healthcheck:
         test: ['CMD', 'curl', '-f', 'http://172.23.0.2:5432']
         interval: 30s
         timeout: 10s
         retries: 5

   web:
      container_name: django
      build:
         context: ./server
         dockerfile: Dockerfile
      command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py loadseed seed.json && python manage.py runserver 0.0.0.0:8000"

      volumes:
         - ./server:/code
      ports:
         - 8000:8000
      restart: on-failure
      depends_on:
         - db
      links:
         - db

   client:
      container_name: client
      build:
         context: ./client
         dockerfile: Dockerfile
      command: npm run dev
      volumes:
         - /app/node_modules
         - ./client:/app
      environment:
         - WATCHPACK_POLLING=true
      ports:
         - 3000:3000
