# Generated by Django 4.1 on 2022-09-01 07:56

from django.db import migrations, models
import django.db.models.deletion
import kanban.models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban.column'),
        ),
        migrations.AlterField(
            model_name='card',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='column',
            name='index',
            field=models.IntegerField(default=kanban.models.incrementColumnIndexByOne),
        ),
    ]
