# Generated by Django 4.1 on 2022-09-02 03:58

from django.db import migrations, models
import kanban.models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_alter_card_column_alter_card_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='index',
            field=models.IntegerField(default=kanban.models.incrementCardIndexByOne),
        ),
    ]
